version: 2

builds:
  - main: ./main.go
    ldflags: "-s -w -X main.PRIVATE_KEY={{.Env.PRIVATE_KEY}}"
    id: "prime-monitor"
    dir: ./cli
    binary: prime-monitor
    env:
      - CGO_ENABLED=1
    goos:
      - linux
      - darwin

archives:
  - format: tar.gz
    id: "prime-monitor"
    wrap_in_directory: false
    builds: 
      - "prime-monitor"
    name_template: >-
      prime-monitor_{{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
