x-monitor-env: &monitor-env
  environment:
    - SERVICE_HTTP_WEB=web:3000
    - SERVICE_HTTP_API=api:8000
    - SERVICE_HTTP_PROXY=proxy:80
    - SERVICE_HTTP_MINIO=plane-minio:9090
    - SERVICE_TCP_REDIS=plane-redis:6379
    - SERVICE_TCP_POSTGRES=plane-db:5432
    - TRUSTED_PROXIES=${TRUSTED_PROXIES:-0.0.0.0/0}

x-proxy-env: &proxy-env
  environment:
    - SITE_ADDRESS=${SITE_ADDRESS:-localhost:80}
    - CERT_EMAIL=${CERT_EMAIL:-admin@example.com}
    - CERT_ACME_CA=${CERT_ACME_CA:-}
    - CERT_ACME_DNS=${CERT_ACME_DNS:-}
    - BUCKET_NAME=${BUCKET_NAME:-uploads}
    - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
    - LISTEN_HTTP_PORT=${LISTEN_HTTP_PORT:-80}
    - LISTEN_HTTPS_PORT=${LISTEN_HTTPS_PORT:-443}

x-app-env: &app-env
  environment:
    - WEB_URL=${WEB_URL:-http://localhost}
    - DEBUG=${DEBUG:-0}
    - SENTRY_DSN=${SENTRY_DSN:-""}
    - SENTRY_ENVIRONMENT=${SENTRY_ENVIRONMENT:-"production"}
    - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-}
    # Gunicorn Workers
    - GUNICORN_WORKERS=${GUNICORN_WORKERS:-2}
    #DB SETTINGS
    - PGHOST=${PGHOST:-plane-db}
    - PGDATABASE=${PGDATABASE:-plane}
    - POSTGRES_USER=${POSTGRES_USER:-plane}
    - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-plane}
    - POSTGRES_DB=${POSTGRES_DB:-plane}
    - PGDATA=${PGDATA:-/var/lib/postgresql/data}
    - DATABASE_URL=${DATABASE_URL:-postgresql://plane:plane@plane-db/plane}
    # REDIS SETTINGS
    - REDIS_HOST=${REDIS_HOST:-plane-redis}
    - REDIS_PORT=${REDIS_PORT:-6379}
    - REDIS_URL=${REDIS_URL:-redis://plane-redis:6379/}
    # Application secret
    - SECRET_KEY=${SECRET_KEY:-60gp0byfz2dvffa45cxl20p1scy9xbpf6d8c5y0geejgkyp1b5}
    # DATA STORE SETTINGS
    - USE_MINIO=${USE_MINIO:-1}
    - AWS_REGION=${AWS_REGION:-""}
    - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID:-"access-key"}
    - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY:-"secret-key"}
    - AWS_S3_ENDPOINT_URL=${AWS_S3_ENDPOINT_URL:-http://plane-minio:9000}
    - AWS_S3_BUCKET_NAME=${AWS_S3_BUCKET_NAME:-uploads}
    - MINIO_ROOT_USER=${MINIO_ROOT_USER:-"access-key"}
    - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD:-"secret-key"}
    - BUCKET_NAME=${BUCKET_NAME:-uploads}
    - FILE_SIZE_LIMIT=${FILE_SIZE_LIMIT:-5242880}
    - SSL_VERIFY=${SSL_VERIFY:-1}
    - FEATURE_FLAG_SERVER_BASE_URL=${FEATURE_FLAG_SERVER_BASE_URL:-http://monitor:8080}
    - PAYMENT_SERVER_BASE_URL=${PAYMENT_SERVER_BASE_URL:-http://monitor:8080}

services:
  admin:
    <<: *app-env
    image: registry.plane.tools/plane/admin-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node admin/server.js admin
    deploy:
      replicas: ${ADMIN_REPLICAS:-1}
    depends_on:
      - api
      - web

  web:
    <<: *app-env
    image: registry.plane.tools/plane/web-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node web/server.js web
    deploy:
      replicas: ${WEB_REPLICAS:-1}
    depends_on:
      - api
      - worker

  monitor:
    <<: *monitor-env
    image: registry.plane.tools/plane/monitor-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped

  space:
    <<: *app-env
    image: registry.plane.tools/plane/space-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: node space/server.js space
    deploy:
      replicas: ${SPACE_REPLICAS:-1}
    depends_on:
      - api
      - worker
      - web

  api:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-api-ee.sh
    deploy:
      replicas: ${API_REPLICAS:-1}
    volumes:
      - ${INSTALL_DIR}/logs/api:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis

  worker:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-worker.sh
    volumes:
      - ${INSTALL_DIR}/logs/worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis

  beat-worker:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: unless-stopped
    command: ./bin/docker-entrypoint-beat.sh
    volumes:
      - ${INSTALL_DIR}/logs/beat-worker:/code/plane/logs
    depends_on:
      - api
      - plane-db
      - plane-redis

  migrator:
    <<: *app-env
    image: registry.plane.tools/plane/backend-enterprise:${APP_RELEASE_VERSION}
    restart: "no"
    command: ./bin/docker-entrypoint-migrator.sh
    volumes:
      - ${INSTALL_DIR}/logs/migrator:/code/plane/logs
    depends_on:
      - plane-db
      - plane-redis

  plane-db:
    <<: *app-env
    image: registry.plane.tools/plane/postgres:15.5-alpine
    restart: unless-stopped
    command: postgres -c 'max_connections=1000'
    volumes:
      - ${INSTALL_DIR}/data/db:/var/lib/postgresql/data

  plane-redis:
    <<: *app-env
    image: registry.plane.tools/plane/valkey:7.2.5-alpine
    restart: unless-stopped
    volumes:
      - ${INSTALL_DIR}/data/redis:/data

  plane-minio:
    <<: *app-env
    image: registry.plane.tools/plane/minio:latest
    restart: unless-stopped
    command: server /export --console-address ":9090"
    volumes:
      - ${INSTALL_DIR}/data/minio/uploads:/export
      - ${INSTALL_DIR}/data/minio/data:/data

  # Comment this if you already have a reverse proxy running
  proxy:
    <<: *proxy-env
    image: registry.plane.tools/plane/caddy:latest
    restart: unless-stopped
    ports:
      - ${LISTEN_HTTP_PORT:-80}:${LISTEN_HTTP_PORT:-80}
      - ${LISTEN_HTTPS_PORT:-443}:${LISTEN_HTTPS_PORT:-443}
    volumes:
      - ${INSTALL_DIR}/Caddyfile:/etc/caddy/Caddyfile
      - ${INSTALL_DIR}/caddy/config:/config
      - ${INSTALL_DIR}/caddy/data:/data
    depends_on:
      - web
      - api
      - space
