name: Build & Deploy on main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        id: meta
        run: echo "tag=main-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Compute lowercase owner
        id: vars
        run: echo "owner=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: backend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-backend:${{ steps.meta.outputs.tag }}

      - name: Build & push frontend
        uses: docker/build-push-action@v6
        with:
          context: .
          file: frontend/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-frontend:${{ steps.meta.outputs.tag }}

      - name: Build & push admin
        uses: docker/build-push-action@v6
        with:
          context: .
          file: admin/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-admin:${{ steps.meta.outputs.tag }}

      - name: Build & push space
        uses: docker/build-push-action@v6
        with:
          context: .
          file: space/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-space:${{ steps.meta.outputs.tag }}

      - name: Build & push live
        uses: docker/build-push-action@v6
        with:
          context: .
          file: live/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-live:${{ steps.meta.outputs.tag }}

      - name: Build & push proxy
        uses: docker/build-push-action@v6
        with:
          context: .
          file: proxy/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-proxy:${{ steps.meta.outputs.tag }}

  deploy:
    name: Deploy to Hetzner
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            cd /opt/plane
            bash deploy.sh "${{ needs.build.outputs.tag }}"