name: Build & Deploy on main

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    outputs:
      tag: ${{ steps.meta.outputs.tag }}
      owner: ${{ steps.vars.outputs.owner }}

    steps:
      - uses: actions/checkout@v4

      - name: Compute image tag
        id: meta
        run: echo "tag=main-$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Lowercase owner
        id: vars
        run: echo "owner=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT

      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push AIO image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: deployments/aio/community/Dockerfile
          push: true
          platforms: linux/amd64
          tags: ghcr.io/${{ steps.vars.outputs.owner }}/furlong-aio:${{ steps.meta.outputs.tag }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT || 22 }}
          script: |
            set -e
            cd /opt/furlong
            # Pull the AIO image
            docker pull ghcr.io/${{ needs.build.outputs.owner }}/furlong-aio:${{ needs.build.outputs.tag }}
            # Stop any existing containers
            docker stop furlong-aio || true
            docker rm furlong-aio || true
            # Run the AIO container
            docker run -d \
              --name furlong-aio \
              --restart unless-stopped \
              -p 80:80 \
              -p 443:443 \
              -v furlong-data:/app/data \
              -v furlong-logs:/app/logs \
              ghcr.io/${{ needs.build.outputs.owner }}/furlong-aio:${{ needs.build.outputs.tag }}