name: Upstream Sync
on:
  schedule:
    - cron: "0 7 * * 1"   # Mondays 07:00 UTC
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add upstream & fetch
        run: |
          git remote add upstream https://github.com/makeplane/plane.git || true
          git fetch upstream --tags

      - name: Merge upstream/main into a sync branch
        run: |
          git checkout -B chore/upstream-sync
          if ! git merge --no-edit upstream/main; then
            echo "Merge failed! Please resolve conflicts manually."
            exit 1
          fi
          git push -u origin chore/upstream-sync --force

      - name: Check for changes
        id: check_diff
        run: |
          git fetch origin main
          if git diff --quiet origin/main chore/upstream-sync; then
            echo "has_changes=false" >> $GITHUB_OUTPUT
          else
            echo "has_changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Open PR
        if: steps.check_diff.outputs.has_changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          branch: chore/upstream-sync
          title: "Sync: upstream/main → main"
          body: "Automated upstream sync. Review, test, merge to deploy."
          base: main
          labels: upstream-sync
